FROM golang:1.14
ADD data_source /src/data_source
ADD parsing /src/parsing
ADD server /src/server
ADD main.go /src/main.go
ADD go.mod /src/go.mod
ADD go.sum /src/go.sum
WORKDIR /src
EXPOSE 8080 9000
CMD go run main.go
