version: "2"
services:
    note-api:
        build: ./deployments
        volumes:
            - ./:/src/
        working_dir: /src
        command: gin -a 8080 -b gin-note -i run main.go
        environment:
          - REDIS_HOST=note-redis
          - REDIS_PORT=6378
          - TABLE=tag
        ports:
          - 8080:8080
        depends_on:
          - note-redis
    note-redis:
      image: redis:alpine
      command: --port 6378
      ports:
        - 6378:6378

    synonym-api:
        build: ./deployments
        volumes:
            - ./:/src/
        working_dir: /src
        command: gin -a 8080 --all -i run main.go
        restart: always
        environment:
          - REDIS_HOST=synonym-redis
          - REDIS_PORT=6378
          - TABLE=synonym
        ports:
          - 8081:8080
        depends_on:
          - synonym-redis
    synonym-redis:
      image: redis:alpine
      ports:
        - 6380:6379
