apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-server
  template:
    metadata:
      labels:
        app: note-server
    spec:
      containers:
      - name: note-server
        image: shdkej/note-server
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: note-server
  namespace: default
  labels:
    app: note-server
    tier: frontend
spec:
  ports:
  - port: 8080
  selector:
    app: note-server
    tier: frontend
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: note-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: note-server
spec:
  hosts:
  - "*"
  gateways:
  - note-gateway
  http:
  - match:
    - uri:
        exact: /note-server
    route:
    - destination:
        host: note-server
        port:
          number: 8080
