name: Check the Source
on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: vpn.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [all]
          193.122.124.65
        vault_password: ${{secrets.VAULT_PASSWORD}}
        options: |
          --verbose
          -u ubuntu
