name: Check the Source
on:
  push:
    branches: [ feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Note Directory
      run: git clone https://github.com/shdkej/shdkej.github.io /tmp/shdkej.github.io

    - name: Make csv file
      env:
        VIMWIKI: /tmp/shdkej.github.io/content
        CSV_PATH: /tmp/result/tags.csv
      run: |
        cd parsing
        mkdir -p /tmp/result
        go test
        rm -r $VIMWIKI

    - name: Test Code
      run: |
        cd parsing
        go test -race -coverprofile=coverage.txt -covermode=atomic

    - name: Report Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: parsing/coverage.txt

    - id: upload-csv
      name: Upload csv file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CSV_PATH: /tmp/result/tags.csv
      run: |
        cd lambda
        go test -cover -v > output.txt
        body=$(cat output.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"
        echo "::set-output name=body::$body"

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "${{ github.ref }} into master"
        pr_body: "${{ steps.upload-csv.outputs.body }}"
