name: go build test
on: ["pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calc coverage
        run: |
          go test -v -coverprofile=profile.cov ./...

      - name: goveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

      - name: Fail Alert
        uses: actions/github-script@0.3.0
        #if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Failed' });
