name: Pull Request
on:
  push:
    branches: [ feature/* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: use nodejs 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get Tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "${{ github.ref }} into master"
        pr_body: ":robot: need template"
        pr_label: "auto-pr"
