name: Pull Request
on:
  push:
    branches: [ feature/* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "${{ github.ref }} into master"
        pr_body: ":robot: need template"
        pr_label: "auto-pr"
