name: Pull Request
on:
  push:
    branches: [ feature/* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: use nodejs 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set Tag
      id: tag
      run: echo ::set-ouptut name=TAG::${GITHUB_REF#refs/tags/}
    - name: Build image
      #run: docker build . --file Dockerfile-build --tag ${{ steps.tag.outputs.TAG }}
      run: echo ${{ steps.tag.outputs.TAG }}

    - name: standard versioning
      run: |
        npm i -g standard-version
        git config --global user.email "shdkej@github.com"
        git config --global user.name "shdkej"
        standard-version
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "${{ github.ref }} into master"
        pr_body: ":robot: need template"
        pr_label: "auto-pr"
